from __future__ import annotations
from typing import Protocol, List, Tuple
from chess_coach.domain.models import Game


class GameRepository(Protocol):
    def save_games(self, games: List[Game], username: str) -> None: ...
    def list_recent_games(self, username: str, limit: int) -> List[Game]: ...

    def save_puzzles(self, username: str, platform: str, puzzles: List[Tuple]) -> None: ...
    def list_puzzles(self, username: str, limit: int = 10): ...
